name: christinewraight
favicon: null
layout_spectrum: 0.6042553544975817
typography_spectrum: 0.6228395940270275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2004981879144907
  lightness: 0.6402725980151445
  saturation: 0.5047579165548086
  rhythmicContrast: 0.3927393574267626
purpose: []
