name: Christine Wraight
favicon: null
layout_spectrum: 0.49517
typography_spectrum: 0.6228395940270275
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73372125-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5625
  lightness: 0.6402725980151445
  saturation: 0.625
  rhythmicContrast: 0.3927393574267626
purpose: []
