name: Christine Wraight
favicon: null
layout_spectrum: 0.47588
typography_spectrum: 0.96421
title: Frei Journalistin und PR Beraterin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73362420-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#242021'
    - '#d5d4d4'
    - '#625f60'
    - '#878585'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
